// <auto-generated />
using System;
using ManthanGurukul.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ManthanGurukul.Infrastructure.Migrations
{
    [DbContext(typeof(ManthanGurukulDBContext))]
    partial class ManthanGurukulDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ManthanGurukul.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<long>("MobileNo")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModifiedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("MobileNo", "Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4715f47-7de9-45e1-80fc-c6ea6e6eadde"),
                            CreatedAt = 638836672468805628L,
                            CreatedBy = new Guid("a4715f47-7de9-45e1-80fc-c6ea6e6eadde"),
                            Email = "nishant.kumar.mishra@gmail.com",
                            FirstName = "Nishant",
                            IsActive = true,
                            LastName = "Mishra",
                            MobileNo = 9945654327L,
                            PasswordHash = new byte[] { 166, 47, 200, 85, 51, 238, 238, 80, 81, 102, 36, 176, 34, 225, 121, 132, 118, 242, 164, 179, 175, 17, 50, 88, 154, 0, 114, 142, 171, 143, 253, 173, 220, 54, 250, 189, 103, 62, 212, 146, 30, 38, 59, 45, 0, 250, 200, 196, 98, 211, 110, 133, 167, 167, 189, 157, 7, 11, 56, 73, 44, 94, 215, 220 },
                            PasswordSalt = new byte[] { 105, 90, 183, 69, 204, 241, 196, 168, 36, 49, 221, 118, 238, 204, 97, 92, 164, 169, 248, 130, 56, 55, 221, 183, 175, 88, 128, 127, 90, 13, 34, 222, 232, 184, 230, 177, 215, 89, 54, 29, 146, 50, 168, 225, 42, 150, 184, 147, 66, 169, 184, 227, 165, 226, 22, 178, 134, 134, 223, 123, 79, 111, 110, 105, 144, 104, 127, 168, 35, 170, 143, 235, 184, 224, 165, 252, 190, 117, 247, 109, 142, 54, 164, 140, 187, 9, 138, 129, 39, 119, 121, 61, 60, 72, 215, 75, 175, 211, 17, 198, 174, 182, 119, 78, 38, 199, 14, 216, 177, 189, 223, 230, 141, 224, 77, 126, 180, 108, 229, 198, 200, 135, 139, 31, 77, 170, 164, 1 }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
